/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hbzhu' at '11/1/16 7:02 PM' with Gradle 2.14.1
 *
 * @author hbzhu, @date 11/1/16 7:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
